from comfy_api.latest import io


VIDEO_TIMELINE = io.Custom("VIDEO_TIMELINE")
TIMELINE_VALIDATION = io.Custom("TIMELINE_VALIDATION")
DEBUG_INFO = io.Custom("DEBUG_INFO")

LTX_TIMELINE_CONFIG = io.Custom("LTX_TIMELINE_CONFIG")
LTX_TIMELINE_PLAN = io.Custom("LTX_TIMELINE_PLAN")
IC_LORA_PARAMETERS = io.Custom("IC_LORA_PARAMETERS")

WAN_TIMELINE_CONFIG = io.Custom("WAN_TIMELINE_CONFIG")
WAN_TIMELINE_PLAN = io.Custom("WAN_TIMELINE_PLAN")

GUIDE_DATA = io.Custom("GUIDE_DATA")
LTX_IDENTITY_ANCHOR = io.Custom("LTX_IDENTITY_ANCHOR")
