SCHEMA_VERSION = "2.0"
VIDEO_TIMELINE_TYPE = "VIDEO_TIMELINE"

SECTION_TYPE_IMAGE = "Image"
SECTION_TYPE_TEXT = "Text"
SECTION_TYPE_VIDEO = "Video"
SECTION_TYPES = (SECTION_TYPE_IMAGE, SECTION_TYPE_TEXT, SECTION_TYPE_VIDEO)

ASSET_TYPE_IMAGE = "Image"
ASSET_TYPE_VIDEO = "Video"
ASSET_TYPE_AUDIO = "Audio"
ASSET_TYPES = (ASSET_TYPE_IMAGE, ASSET_TYPE_VIDEO, ASSET_TYPE_AUDIO)

ASSET_SOURCE_FILE_PATH = "FilePath"
ASSET_SOURCE_UPLOADED_FILE = "UploadedFile"
ASSET_SOURCE_GENERATED = "Generated"
ASSET_SOURCE_COMFYUI_INPUT = "ComfyUIInput"
ASSET_SOURCE_KINDS = (
    ASSET_SOURCE_FILE_PATH,
    ASSET_SOURCE_UPLOADED_FILE,
    ASSET_SOURCE_GENERATED,
    ASSET_SOURCE_COMFYUI_INPUT,
)

CROP_MODE_PROJECT_DEFAULT = "Project Default"
CROP_MODE_CROP = "Crop"
CROP_MODE_PAD = "Pad"
CROP_MODE_STRETCH_TO_FIT = "Stretch to Fit"
CROP_MODE_KEEP_ASPECT_RATIO = "Keep Aspect Ratio"
CROP_MODES = (
    CROP_MODE_PROJECT_DEFAULT,
    CROP_MODE_CROP,
    CROP_MODE_PAD,
    CROP_MODE_STRETCH_TO_FIT,
    CROP_MODE_KEEP_ASPECT_RATIO,
)

VIDEO_TIMING_FIT_TO_SECTION = "Fit to Section"
VIDEO_TIMING_USE_SOURCE_TIMING = "Use Source Timing"
VIDEO_TIMING_LOOP = "Loop"
VIDEO_TIMING_FREEZE_LAST_FRAME = "Freeze Last Frame"
VIDEO_TIMING_MODES = (
    VIDEO_TIMING_FIT_TO_SECTION,
    VIDEO_TIMING_USE_SOURCE_TIMING,
    VIDEO_TIMING_LOOP,
    VIDEO_TIMING_FREEZE_LAST_FRAME,
)

VIDEO_GUIDANCE_RANGE_LAST_FRAMES = "Last Frames"
VIDEO_GUIDANCE_RANGE_FULL_SOURCE = "Full Source Range"
VIDEO_GUIDANCE_RANGES = (
    VIDEO_GUIDANCE_RANGE_LAST_FRAMES,
    VIDEO_GUIDANCE_RANGE_FULL_SOURCE,
)
VIDEO_GUIDANCE_FRAME_COUNTS = (1, 9, 17, 25, 33, 49, 65)

QUALITY_PRESET_QUICK_DRAFT = "Quick Draft"
QUALITY_PRESET_DRAFT = "Draft"
QUALITY_PRESET_STANDARD = "Standard"
QUALITY_PRESET_HIGH = "High"
QUALITY_PRESET_NATIVE_RESOLUTION = "Native Resolution"
QUALITY_PRESETS = (
    QUALITY_PRESET_QUICK_DRAFT,
    QUALITY_PRESET_DRAFT,
    QUALITY_PRESET_STANDARD,
    QUALITY_PRESET_HIGH,
    QUALITY_PRESET_NATIVE_RESOLUTION,
)

SEQUENCE_ID_MAIN = "main"
SEQUENCE_NAME_MAIN = "Main Timeline"

SHOT_TYPE_GENERATED = "Generated"
SHOT_TYPE_IMPORTED = "Imported"
SHOT_TYPE_EXTENDED = "Extended"
SHOT_TYPE_EDITED = "Edited"
SHOT_TYPE_PLACEHOLDER = "Placeholder"
SHOT_TYPES = (
    SHOT_TYPE_GENERATED,
    SHOT_TYPE_IMPORTED,
    SHOT_TYPE_EXTENDED,
    SHOT_TYPE_EDITED,
    SHOT_TYPE_PLACEHOLDER,
)

BOUNDARY_MODE_HARD_CUT = "Hard Cut"
BOUNDARY_MODE_CONTINUOUS_SHOT = "Continuous Shot"
BOUNDARY_MODE_BLEND_SEAM = "Blend Seam"
BOUNDARY_MODE_TRANSITION = "Transition"
BOUNDARY_MODES = (
    BOUNDARY_MODE_HARD_CUT,
    BOUNDARY_MODE_CONTINUOUS_SHOT,
    BOUNDARY_MODE_BLEND_SEAM,
    BOUNDARY_MODE_TRANSITION,
)

TAKE_STATUS_CANDIDATE = "Candidate"
TAKE_STATUS_ACCEPTED = "Accepted"
TAKE_STATUS_REJECTED = "Rejected"
TAKE_STATUSES = (
    TAKE_STATUS_CANDIDATE,
    TAKE_STATUS_ACCEPTED,
    TAKE_STATUS_REJECTED,
)

LORA_MERGE_MODE_INHERIT_GLOBAL = "Inherit Global"
LORA_MERGE_MODE_ADD_TO_GLOBAL = "Add To Global"
LORA_MERGE_MODE_REPLACE_GLOBAL = "Replace Global"
LORA_MERGE_MODE_DISABLE_LORAS = "Disable LoRAs"
LORA_MERGE_MODES = (
    LORA_MERGE_MODE_INHERIT_GLOBAL,
    LORA_MERGE_MODE_ADD_TO_GLOBAL,
    LORA_MERGE_MODE_REPLACE_GLOBAL,
    LORA_MERGE_MODE_DISABLE_LORAS,
)

MODEL_LORA_SCHEMA_VERSION = 2
MODEL_LORA_MODEL_LTX_2_3 = "ltx_2_3"
MODEL_LORA_MODEL_WAN_2_2 = "wan_2_2"
MODEL_LORA_TARGET_MAIN = "main"
MODEL_LORA_TARGET_HIGH_NOISE = "high_noise"
MODEL_LORA_TARGET_LOW_NOISE = "low_noise"

TIMELINE_DISPLAY_MODE_DEFAULT = "Sections"
SECTION_EDIT_MODE_TRIM_NEIGHBOR = "Trim Neighbor"
SNAP_MODE_NONE = "None"
SNAP_MODE_SECONDS = "Seconds"
SNAP_MODE_FRAMES = "Frames"

GLOBAL_PROMPT_POSITION_PREFIX = "Prefix"
GLOBAL_PROMPT_POSITION_SUFFIX = "Suffix"
GLOBAL_PROMPT_POSITIONS = (
    GLOBAL_PROMPT_POSITION_PREFIX,
    GLOBAL_PROMPT_POSITION_SUFFIX,
)

DEFAULT_DURATION_SECONDS = 5.0
DEFAULT_FRAME_RATE = 24.0
DEFAULT_ASPECT_RATIO = "16:9"
DEFAULT_ORIENTATION = "Landscape"
DEFAULT_QUALITY_PRESET = QUALITY_PRESET_STANDARD

DEFAULT_ALLOW_GAPS = True
DEFAULT_AUTO_CLOSE_GAPS = False
DEFAULT_MINIMUM_SECTION_DURATION_SECONDS = 0.25
DEFAULT_IMAGE_GUIDE_STRENGTH = 1.0
DEFAULT_VIDEO_GUIDE_STRENGTH = 1.0
DEFAULT_VIDEO_TIMING_MODE = VIDEO_TIMING_FIT_TO_SECTION
DEFAULT_VIDEO_GUIDANCE_RANGE = VIDEO_GUIDANCE_RANGE_LAST_FRAMES
DEFAULT_VIDEO_GUIDANCE_FRAME_COUNT = 17
DEFAULT_USE_NATIVE_AUDIO = False
DEFAULT_AUDIO_VOLUME = 100.0
DEFAULT_AUDIO_FADE_IN_SECONDS = 0.0
DEFAULT_AUDIO_FADE_OUT_SECONDS = 0.0
